events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    gzip on;
    gzip_types text/plain application/json application/javascript text/css;

    upstream api {
        server api:8000;
    }

    server {
        listen 80;
        server_name _;

        location /admin/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /admin/index.html;
            add_header Cache-Control "max-age=86400";
        }

        location / {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
